In [38]:
from sklearn.preprocessing import normalize, MinMaxScaler, minmax_scale
import numpy as np
import pandas as pd

In [43]:
x = np.array([[5.0, 4.0, 3.0, 2.0, 1.0]])

In [47]:
norms = row_norms(x)

NameError: name 'row_norms' is not defined

In [45]:
norms

array([ 15.])

In [48]:
normalize(x, norm='l2')

array([[ 0.67419986,  0.53935989,  0.40451992,  0.26967994,  0.13483997]])

In [36]:
minmax_scale(x)

array([ 1.  ,  0.75,  0.5 ,  0.25,  0.  ])

In [37]:
x

array([ 5.,  4.,  3.,  2.,  1.])